YAHOO_PAGER_HOST = "scsa.msg.yahoo.com"
YAHOO_PAGER_PORT = 5050


YAHOO_TOKEN_URL = "https://login.yahoo.com/config/pwtoken_get?src=ymsgr" \
                    "&ts=&login=%s&passwd=%s&chal=%s"
YAHOO_LOGIN_URL = "https://login.yahoo.com/config/pwtoken_login?src=ymsgr" \
                    "&ts=&token=%s"


YAHOO_SERVICE_LOGON     = 0x01
YAHOO_SERVICE_LOGOFF    = 0x02
YAHOO_SERVICE_MESSAGE   = 0x06
YAHOO_SERVICE_PING      = 0x12
YAHOO_SERVICE_HANDSHAKE = 0x4C
YAHOO_SERVICE_AUTHRESP  = 0x54
YAHOO_SERVICE_AUTH      = 0x57


YAHOO_STATUS_AVAILABLE  = 0x00
YAHOO_STATUS_BRB        = 0x01
YAHOO_STATUS_BUSY       = 0x02
YAHOO_STATUS_NOTATHOME  = 0x03
YAHOO_STATUS_NOTATDESK  = 0x04
YAHOO_STATUS_NOTINOFFICE= 0x05
YAHOO_STATUS_ONPHONE    = 0x06
YAHOO_STATUS_ONVACATION = 0x07
YAHOO_STATUS_OUTTOLUNCH = 0x08
YAHOO_STATUS_STEPPEDOUT = 0x09
YAHOO_STATUS_INVISIBLE  = 0x0c
YAHOO_STATUS_CUSTOM     = 0x63


YAHOO_RETCODE_OK                = 0x01
YAHOO_RETCODE_ERR_SRVCON        = 0x02
YAHOO_RETCODE_ERR_UPMISSING     = 0x03
YAHOO_RETCODE_ERR_UHASAT        = 0x04
YAHOO_RETCODE_ERR_LOGIN         = 0x05
YAHOO_RETCODE_ERR_UDEACTIVATED  = 0x06
YAHOO_RETCODE_ERR_UNOTEXIST     = 0x07
YAHOO_RETCODE_ERR_LOCKED        = 0x08
